import "./globals.css";

import Header from "@/components/ui/Header";
import PageTransition from "@/components/ui/PageTransition";
import StairTransition from '@/components/ui/StairTransition';

const Layout = ({ children }) => {
  return (
    <html lang="fr">
      <body className="antialiased" style={{ fontFamily: 'Bahnschrift, sans-serif' }}>
        <Header />
        {/* Stairs animation */}
        <StairTransition />
        {/* Page transition */}
        <PageTransition>
          {children}
        </PageTransition>
      </body>
    </html>
  );
};

export const metadata = {
  title: "Oskil Portfolio",
  description: "Generated by create next app",
};

export default Layout;
